services:
  - type: web
    name: summarizer-api
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    plan: free
    autoDeploy: true
